#ifndef PROJECTEXPLORER_GLOBAL_H
#define PROJECTEXPLORER_GLOBAL_H

#include <QtGlobal>

#if defined(PROJECTEXPLORER_LIBRARY)
#  define PROJECTEXPLORER_EXPORT Q_DECL_EXPORT
#else
#  define PROJECTEXPLORER_EXPORT Q_DECL_IMPORT
#endif

#endif // PROJECTEXPLORER_GLOBAL_H
